### ISSUE TITLE
お知らせのスタイルを修正する

### ISSUE THREAD

**Issue by Na0ki** [Na0ki/mastodon#8]
mikutterのお知らせ欄のスタイルが崩れている。  
mastodon側にannouncementsが追加されたことによる影響の模様。  

修正するにあたっては以下が参考になる。  
https://github.com/lindwurm/mastodon/pull/23

**Comment by Na0ki** [comment]
@toshia @akkiesoft お時間あればステージングで崩れが直ってることを確認してくだしあ

**Comment by toshia** [comment]
LGTM
